[package]
name = 'dagora_launchpad'
version = '1.0.0'

[addresses]
DagoraLaunchpad = "d849853cbe1ae22a80eebf1d57bc0d0258b8c72e8cea601653f994ffaf7132d3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev="devnet"}
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev="devnet"}